- name: Disable and stop multipathd service
  systemd:
    name: multipathd
    enabled: false
    state: stopped
  become: true
  ignore_errors: true # We don't want to fail if multipathd is not installed
