- name: Format, partition, and mount disks
  ansible.builtin.include_role:
    name: mounted_drive
  vars:
    mounted_drive_target_device: "{{ storage.longhorn.volume.device }}"
    mounted_drive_target_partition: "{{ storage.longhorn.volume.partition }}"
    mounted_drive_mount_point: "{{ storage.longhorn.volume.path }}"
