- name: Gather service facts
  ansible.builtin.service_facts:

- name: Disable and stop multipathd service
  ansible.builtin.systemd:
    name: multipathd
    enabled: false
    state: stopped
  become: true
  vars:
    available_services: "{{ ansible_facts.services | map(attribute='name') }}"
  when: "'multipathd.service' in available_services"
