mounted_drive_target_device: ""
mounted_drive_partition_start: "0%"
mounted_drive_partition_end: "100%"
mounted_drive_filesystem: "ext4"
mounted_drive_mount_point: "/mnt/data"
mounted_drive_mount_point_owner: "root"
mounted_drive_mount_point_group: "root"
mounted_drive_mount_point_mode: "0755"
