- name: Check preflight
  ansible.builtin.command:
    cmd: "longhornctl --kube-config {{ kubeconfig.path }} --image longhornio/longhorn-cli:v{{ storage.longhorn.cli.version }} check preflight"
  register: longhorn_base_preflight_check
  failed_when: longhorn_base_preflight_check.rc != 0
  changed_when: false
  become: true

- name: Check preflight
  ansible.builtin.command:
    cmd: "longhornctl --kube-config {{ kubeconfig.path }} --image longhornio/longhorn-cli:v{{ storage.longhorn.cli.version }} install preflight"
  register: longhorn_base_preflight_check
  failed_when: longhorn_base_preflight_check.rc != 0
  changed_when: false
  become: true
