storage:
  velero:
    cli:
      arch: "arm64"
      version: "1.17.1"
      download_url: "https://github.com/vmware-tanzu/velero/releases/download/v{{ storage.velero.cli.version }}/velero-v{{ storage.velero.cli.version }}-linux-{{ storage.velero.cli.arch }}.tar.gz"
      install_dir: "/usr/local/bin"
