- name: Install dependencies
  ansible.builtin.import_tasks: install_dependencies.yml

- name: Configure kernel modules
  ansible.builtin.import_tasks: configure_kernel_modules.yml

- name: Configure multipathd
  ansible.builtin.import_tasks: configure_multipathd.yml

- name: Install longhotnctl
  ansible.builtin.import_tasks: install_longhornctl.yml

- name: Run preflight checks
  ansible.builtin.import_tasks: run_preflight_checks.yml
